import { Octokit } from "@octokit/rest";

// const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

export interface OpenPrParams {
	repositoryUrl: string;
	baseBranch: string;
	filePath: string;
	newContent: string;
	fixId: string;
	incidentTitle: string;
	explanation: string;
	riskLevel: "low" | "medium" | "high";
	diagnosis: { rootCause: string; confidence: number };
	testResults: { reproductionPassed: boolean; regressionPassed: boolean };
}

export interface OpenPrResult {
	branch: string;
	number: number;
	url: string;
}

function parseOwnerRepo(repositoryUrl: string) {
	const url = new URL(repositoryUrl);
	const [owner, repo] = url.pathname
		.replace(/^\//, "")
		.replace(/\.git$/, "")
		.split("/");
	return { owner, repo };
}

export async function openPullRequest(
	token: string,
	params: OpenPrParams,
): Promise<OpenPrResult> {
	const { owner, repo } = parseOwnerRepo(params.repositoryUrl);
	const branch = `modulus/fix-${params.fixId.slice(0, 8)}`;
	const octokit = new Octokit({ auth: token });

	const baseRef = await octokit.git.getRef({
		owner,
		repo,
		ref: `heads/${params.baseBranch}`,
	});
	await octokit.git.createRef({
		owner,
		repo,
		ref: `refs/heads/${branch}`,
		sha: baseRef.data.object.sha,
	});

	const existing = await octokit.repos
		.getContent({ owner, repo, path: params.filePath, ref: branch })
		.catch(() => null);
	const existingSha =
		existing && !Array.isArray(existing.data) ? existing.data.sha : undefined;

	await octokit.repos.createOrUpdateFileContents({
		owner,
		repo,
		branch,
		path: params.filePath,
		message: `fix: ${params.incidentTitle}`,
		content: Buffer.from(params.newContent, "utf-8").toString("base64"),
		sha: existingSha,
	});

	const reviewNote =
		params.riskLevel === "medium"
			? "\n\n**⚠️ Medium risk — please review before merging.**"
			: "";

	// DoD requirement made literal: "a GitHub PR containing the diagnosis, change, and verification results"
	const body = [
		`Automatically generated by Modulus for **${params.incidentTitle}**.`,
		``,
		`### Root cause`,
		params.diagnosis.rootCause,
		`_Diagnosis confidence: ${(params.diagnosis.confidence * 100).toFixed(0)}%_`,
		``,
		`### Change`,
		params.explanation,
		``,
		`### Verification`,
		`- Confirmed reproducing on the target commit before this fix`,
		`- Reproduction test after fix: ${params.testResults.reproductionPassed ? "✅ no longer reproduces" : "❌ still reproduces"}`,
		`- Regression suite: ${params.testResults.regressionPassed ? "✅ passing" : "❌ failing"}`,
		reviewNote,
		``,
		`_Risk level: ${params.riskLevel}_`,
	].join("\n");

	const pr = await octokit.pulls.create({
		owner,
		repo,
		title: `Fix: ${params.incidentTitle}`,
		head: branch,
		base: params.baseBranch,
		body,
	});
	return { branch, number: pr.data.number, url: pr.data.html_url };
}

// fetch status
export async function fetchPullRequestStatus(
	token: string,
	repositoryUrl: string,
	prNumber: number,
): Promise<"open" | "merged" | "closed"> {
	const octokit = new Octokit({ auth: token });
	const { owner, repo } = parseOwnerRepo(repositoryUrl);
	const pr = await octokit.pulls.get({ owner, repo, pull_number: prNumber });
	if (pr.data.merged) return "merged";
	return pr.data.state === "closed" ? "closed" : "open";
}